{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django.configMapName" . }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
data:
  {{- include "django.configData" . | trim | nindent 2 }}
{{- end }}
